# Generated by Django 4.2.5 on 2023-09-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Учебного центра',
                'verbose_name_plural': 'Учебные центры',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=256)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учители',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('phone_number', models.CharField(max_length=256)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'verbose_name': 'Учебного центра',
                'verbose_name_plural': 'Учебные центры',
            },
        ),
    ]
